/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelos.Estudiante;
import Modelos.Cursos;
import javax.swing.JOptionPane;

/**
 *
 * @author romar
 */
public class JDAgregarCurso extends javax.swing.JDialog {
    
    
    /**
     * Creates new form JDAgregarCurso
     */
    public JDAgregarCurso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoCarreras = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombrecur = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnCarrera1 = new javax.swing.JRadioButton();
        btnCarrera2 = new javax.swing.JRadioButton();
        btnCarrera3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setText("Ingreso de cursos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 220, 34));

        jLabel1.setText("Nombre del curso");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        txtNombrecur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombrecurKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombrecur, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 180, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 110, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Carrera del curso"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grupoCarreras.add(btnCarrera1);
        btnCarrera1.setSelected(true);
        btnCarrera1.setText("Administración");
        jPanel1.add(btnCarrera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, -1));

        grupoCarreras.add(btnCarrera2);
        btnCarrera2.setText("Derecho");
        jPanel1.add(btnCarrera2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 92, -1));

        grupoCarreras.add(btnCarrera3);
        btnCarrera3.setText("Medicina");
        jPanel1.add(btnCarrera3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 92, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 180, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        if ((txtNombrecur.getText().equals("")) || (btnCarrera1.getText().equals("")) ||
            (btnCarrera2.getText().equals("")) || (btnCarrera3.getText().equals(""))){
            
            javax.swing.JOptionPane.showMessageDialog(this,"Llene el campo, por favor. \n","AVISO",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            txtNombrecur.requestFocus();
            
                    
        }
        else{
        
           Cursos NC = new Cursos();
            
            if(btnCarrera1.isSelected()){
                JOptionPane.showMessageDialog(null, NC.AgregarCurso("Administración",txtNombrecur.getText()));
                txtNombrecur.setText("");
            }else if(btnCarrera2.isSelected()){
                JOptionPane.showMessageDialog(null, NC.AgregarCurso("Derecho",txtNombrecur.getText()));
                txtNombrecur.setText("");  
            }else{
                JOptionPane.showMessageDialog(null, NC.AgregarCurso("Medicina",txtNombrecur.getText()));
                txtNombrecur.setText("");  
            }
            
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtNombrecurKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombrecurKeyTyped
        
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'á' || c>'ú') && (c<'A' || c>'Z' ) && (c<'Á' || c>'Ú') && (c<' ' || c>' ')) evt.consume();
        
    }//GEN-LAST:event_txtNombrecurKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDAgregarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDAgregarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDAgregarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDAgregarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDAgregarCurso dialog = new JDAgregarCurso(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JRadioButton btnCarrera1;
    private javax.swing.JRadioButton btnCarrera2;
    private javax.swing.JRadioButton btnCarrera3;
    private javax.swing.ButtonGroup grupoCarreras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNombrecur;
    // End of variables declaration//GEN-END:variables
}
