/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelos.Estudiante;
import Modelos.Catedratico;
import Modelos.Cursos;
import Modelos.General;
import static Vistas.JDListadoAlumnos.tablita;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author romar
 */
public class JDAsignarCurso extends javax.swing.JDialog {

Cursos NC = new Cursos();
DefaultTableModel Modelo = new DefaultTableModel();
DefaultTableModel Modelo2 = new DefaultTableModel();


    public JDAsignarCurso(){
        initComponents();
    }

    /**
     * Creates new form JDAsignarCurso
     */
    public JDAsignarCurso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
        NC.llenarCombo(cmbMateria1);
        NC.llenarCombo2(cmbMateria2);
        NC.llenarCombo3(cmbMateria3);
        
        Modelo.addColumn("Carnet");
        Modelo.addColumn("Nombres");
        Modelo.addColumn("Apellidos");
        Modelo.addColumn("Teléfono");
        Modelo.addColumn("Dirección");
        Modelo.addColumn("Correo electrónico");
        tablita.setModel(Modelo);

        Modelo2.addColumn("ID");
        Modelo2.addColumn("Nombres");
        Modelo2.addColumn("Apellidos");
        Modelo2.addColumn("Teléfono");
        Modelo2.addColumn("Dirección");
        Modelo2.addColumn("Correo electrónico");
        tabla.setModel(Modelo2);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoCarreraCurso = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBusquedaC = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtCalendario = new com.toedter.calendar.JCalendar();
        jLabel17 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablita = new javax.swing.JTable();
        grupoCarreras = new javax.swing.JPanel();
        carrera1 = new javax.swing.JRadioButton();
        cmbMateria1 = new javax.swing.JComboBox<>();
        carrera2 = new javax.swing.JRadioButton();
        cmbMateria2 = new javax.swing.JComboBox<>();
        carrera3 = new javax.swing.JRadioButton();
        cmbMateria3 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Asignación de cursos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 260, 40));

        jLabel2.setFont(new java.awt.Font("Sitka Heading", 3, 18)); // NOI18N
        jLabel2.setText("Buscar alumno");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 136, -1));

        jLabel3.setText("Ingese No. de Carnet");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });
        getContentPane().add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 40, 20));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 80, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Heading", 3, 18)); // NOI18N
        jLabel8.setText("Buscar catedrático");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 160, -1));

        jLabel9.setText("Ingese apellido");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));
        jLabel9.getAccessibleContext().setAccessibleName("Ingese appellido");

        txtBusquedaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaCActionPerformed(evt);
            }
        });
        txtBusquedaC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaCKeyTyped(evt);
            }
        });
        getContentPane().add(txtBusquedaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 110, -1));

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 80, -1));

        jLabel15.setFont(new java.awt.Font("Sitka Heading", 3, 18)); // NOI18N
        jLabel15.setText("Carrera y curso");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 130, -1));
        getContentPane().add(txtCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 190, 100));

        jLabel17.setText("Fecha de asignación");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, -1));

        jButton3.setText("Asignar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 200, 42));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 639, 60));

        tablita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Título 5", "Título 6"
            }
        ));
        jScrollPane2.setViewportView(tablita);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 639, 60));

        grupoCarreras.setBorder(javax.swing.BorderFactory.createTitledBorder("CARRERAS"));
        grupoCarreras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grupoCarreraCurso.add(carrera1);
        carrera1.setText("Administración");
        carrera1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carrera1MouseClicked(evt);
            }
        });
        carrera1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrera1ActionPerformed(evt);
            }
        });
        grupoCarreras.add(carrera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 38, -1, -1));

        cmbMateria1.setEnabled(false);
        cmbMateria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMateria1ActionPerformed(evt);
            }
        });
        grupoCarreras.add(cmbMateria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 68, 91, -1));

        grupoCarreraCurso.add(carrera2);
        carrera2.setText("Derecho");
        carrera2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrera2ActionPerformed(evt);
            }
        });
        grupoCarreras.add(carrera2, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 38, -1, -1));

        cmbMateria2.setEnabled(false);
        cmbMateria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMateria2ActionPerformed(evt);
            }
        });
        grupoCarreras.add(cmbMateria2, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 68, 91, -1));

        grupoCarreraCurso.add(carrera3);
        carrera3.setText("Medicina");
        carrera3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrera3ActionPerformed(evt);
            }
        });
        grupoCarreras.add(carrera3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        cmbMateria3.setEnabled(false);
        cmbMateria3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMateria3ActionPerformed(evt);
            }
        });
        grupoCarreras.add(cmbMateria3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 91, -1));

        getContentPane().add(grupoCarreras, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 410, 110));

        jButton4.setText("Ver catedráticos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 130, -1));

        jButton5.setText("Ver alumnos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ((txtBusqueda.getText().equals(""))){
            
            javax.swing.JOptionPane.showMessageDialog(this,"No ingresó No. de carnet. \n","AVISO",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            txtBusqueda.requestFocus();
            
        }
        else{
        
            Estudiante NC = new Estudiante();
            NC.LimpiarLista(Modelo);
            NC.BuscarAlumno(txtBusqueda.getText(),Modelo);
            
        }        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtBusquedaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaCActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            
        if ((txtBusquedaC.getText().equals(""))){
            
            javax.swing.JOptionPane.showMessageDialog(this,"No ingresó apellido. \n","AVISO",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            txtBusquedaC.requestFocus();
            
        }
        else{
            
            Catedratico NC = new Catedratico();
            NC.LimpiarLista(Modelo2);
            NC.BuscarCatedraticoApellido(txtBusquedaC.getText(),Modelo2);
            
            txtBusquedaC.setText("");
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Date fecha = (Date) txtCalendario.getDate();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/d");
        int idCurso;
        if(carrera1.isSelected()){
            idCurso = NC.obteneridCurso((String) cmbMateria1.getSelectedItem());
        }else if (carrera2.isSelected()){
            idCurso = NC.obteneridCurso((String) cmbMateria2.getSelectedItem());    
        }else{
            idCurso = NC.obteneridCurso((String) cmbMateria3.getSelectedItem());    
        }
        DefaultTableModel Modelo =(DefaultTableModel)tablita.getModel();// obtener el modelo de la tabla
        String idAl=(Modelo.getValueAt(tablita.getSelectedRow(),0)+"");
        DefaultTableModel Modelo2 =(DefaultTableModel)tabla.getModel();// obtener el modelo de la tabla
        String idCat=(Modelo2.getValueAt(tabla.getSelectedRow(),0)+"");
        JOptionPane.showMessageDialog(null, NC.AsignarCurso(idAl, idCat, idCurso ,formato.format(fecha)));
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmbMateria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMateria1ActionPerformed
        
    }//GEN-LAST:event_cmbMateria1ActionPerformed

    private void carrera1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carrera1MouseClicked
        
    }//GEN-LAST:event_carrera1MouseClicked

    private void carrera1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrera1ActionPerformed
        
        if(carrera1.isSelected()){
            
            cmbMateria1.setEnabled(true);
            cmbMateria2.setEnabled(false);
            cmbMateria3.setEnabled(false);
            
        }
        
    }//GEN-LAST:event_carrera1ActionPerformed

    private void carrera2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrera2ActionPerformed
        if(carrera2.isSelected()){
            
            cmbMateria1.setEnabled(false);
            cmbMateria2.setEnabled(true);
            cmbMateria3.setEnabled(false);
            
        }
    }//GEN-LAST:event_carrera2ActionPerformed

    private void cmbMateria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMateria2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMateria2ActionPerformed

    private void carrera3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrera3ActionPerformed
        if(carrera3.isSelected()){
            
            cmbMateria1.setEnabled(false);
            cmbMateria2.setEnabled(false);
            cmbMateria3.setEnabled(true);
            
        }
    }//GEN-LAST:event_carrera3ActionPerformed

    private void cmbMateria3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMateria3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMateria3ActionPerformed

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void txtBusquedaCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaCKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'á' || c>'ú') && (c<'A' || c>'Z' ) && (c<'Á' || c>'Ú') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txtBusquedaCKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
       Catedratico NCA = new Catedratico();
       NCA.ListarCatedraticos(Modelo2);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       Estudiante NC = new Estudiante();
       NC.ListarAlumno(Modelo);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDAsignarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDAsignarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDAsignarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDAsignarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDAsignarCurso dialog = new JDAsignarCurso(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton carrera1;
    private javax.swing.JRadioButton carrera2;
    private javax.swing.JRadioButton carrera3;
    public static javax.swing.JComboBox<String> cmbMateria1;
    public static javax.swing.JComboBox<String> cmbMateria2;
    public static javax.swing.JComboBox<String> cmbMateria3;
    private javax.swing.ButtonGroup grupoCarreraCurso;
    private javax.swing.JPanel grupoCarreras;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tabla;
    public static javax.swing.JTable tablita;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtBusquedaC;
    private com.toedter.calendar.JCalendar txtCalendario;
    // End of variables declaration//GEN-END:variables
}
